name 'questions-and-answers-new-app-deploy'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures questions-and-answers-new-app-deploy'
long_description 'Installs/Configures questions-and-answers-new-app-deploy'
version '0.1.15'

depends 'iis'
depends 'windows'
depends 'sql_server'
