source 'https://supermarket.chef.io'

metadata

group :delivery do
  cookbook 'delivery_build', git: 'git://github.com/chef-cookbooks/delivery_build'
  cookbook 'delivery-base', git: 'git://github.com/chef-cookbooks/delivery-base'
end

cookbook 'delivery-truck'
cookbook 'delivery-sugar'
