---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec
#   format: doc

platforms:
  - name: windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[qanda-new-app-deploy::default]
    attributes:
