name 'qanda-new-app-deploy'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures qanda-new-app-deploy'
long_description 'Installs/Configures qanda-new-app-deploy'
version '0.1.2'

depends 'iis'
depends 'windows'
depends 'sql_server'
